### ISSUE TITLE
Qt Transaction Import Implementation

### ISSUE THREAD

**Issue by axjasf** [axjasf/PersonalFinanceCategorizer_WebApp#77]
# Qt Transaction Import Implementation

## Overview
Port the existing transaction import functionality to Qt framework, maintaining feature parity with both:
- Current Streamlit implementation (`pages/02_Import_Transactions.py`)
- Reference Colab implementation ([Bank Files Conversion](https://colab.research.google.com/github/axjasf/Personal-Finance-Categorizer/blob/main/Bank_files_conversion.ipynb))

## Bank-Specific Requirements
- Chase: Standard CSV, category mapping included
- Wells Fargo: Custom header handling, no categories
- Apple Card: Monthly statements, amount sign inversion needed
- Commerzbank: 
  - European date format (DD.MM.YYYY)
  - EUR to USD conversion required
  - German CSV encoding

## Implementation Plan
1. Basic Dialog Structure
   - File selection
   - Bank/Account selection
   - Basic preview
2. Data Processing Integration
   - Field mapping
   - Basic validation
3. Enhanced Features
   - Currency conversion
   - Advanced validation
4. Polish
   - Error handling
   - Progress indication
   - UX improvements

### Dialog Structure
```python
class ImportDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Import Transactions")
        self.setup_ui()
        
    def setup_ui(self):
        # Configuration
        self.bank_combo = QComboBox()
        self.account_combo = QComboBox()
        self.file_button = QPushButton("Select CSV...")
        self.exchange_rate_button = QPushButton("Select Exchange Rates...")
        
        # Preview tables
        self.raw_preview = QTableView()
        self.mapped_preview = QTableView()
        
        # Quality indicators
        self.validation_status = QLabel()
        
        # Import controls
        self.import_button = QPushButton("Import")
        self.progress_bar = QProgressBar()
```

## Testing Requirements
1. **Unit Tests**
   - Dialog initialization
   - File selection
   - Preview updates
   - Import process

2. **Integration Tests**
   - Menu action connection
   - Full import workflow
   - Error handling
   - Data consistency

## Success Criteria
1. Feature parity with Streamlit implementation
2. Maintains compatibility with Colab processing pipeline
3. Successfully processes bank formats
4. Improves UX with native dialogs
5. No regression in data quality

## Dependencies
- Existing import_service.py
- Qt menu framework (#73)
- Field mappings configuration
- Exchange rate data source

## Definition of Done
- [ ] Import dialog implemented
- [ ] Preview grids functional
- [ ] Import process working
- [ ] Tests passing
- [ ] Documentation updated
